// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/domready/domready.d.ts
declare function domready(callback: () => any) : void;

declare module "domready" {
    export = domready;
}
